### PR TITLE
AC coupling options; triggering on both channels; writing output files

### PR DESCRIPTION
**Pull request by rileyle**

### CODE REVIEW

**Comment by davidfokkema** [comment]
Thanks! I really like the AC option, it works well for preamps. In my testing the 'both' triggering option did not work correctly yet. It seemed to remember the previous trigger channel. So when I first had 'A', and then chose 'both', the triggering would stop as soon as I disconnect the 'A' cable (expected) but would continu running when I disconnected only the 'B' cable (unexpected). How does it behave in your setup?

**Comment by rileyle** [comment]
My ‘Both’ label is misleading. I should have called it ‘Either’ or even better ‘A or B’.  Is your observed behavior consistent with a logical OR trigger condition? I’m traveling now but will fix this next week.

My goal was to trigger on either channel, write both channels to disk for each trigger and then do offline sorting to find coincidences.

I haven’t tried A AND B, but I can add that if it’s of interest. In principle it should work. At typical rates, I prefer to have all of the data.

Cheers,

Lew


________________________________

**Comment by davidfokkema** [comment]
> My ‘Both’ label is misleading. I should have called it ‘Either’ or even better ‘A or B’. Is your observed behavior consistent with a logical OR trigger condition? 

It doesn't appear to be so. Disconnecting one of the cables stops the triggering. Which one seems to depend on the previous trigger setting. I agree 'A or B' is a better name.

> I’m traveling now but will fix this next week. My goal was to trigger on either channel, write both channels to disk for each trigger and then do offline sorting to find coincidences. I haven’t tried A AND B, but I can add that if it’s of interest. In principle it should work. At typical rates, I prefer to have all of the data.

Adding 'A and B' would also be nice I think to select coincident annihilation radiation (511 keV). We do rudimentary PET scans by data selection after the fact, but this trigger option would be nice.

Thanks!

**Comment by rileyle** [comment]
I'll look into this.

I may need to use advanced triggering for all of the settings instead of mixing simple and advanced.

I also need to understand how disconnecting a channel affects how it processes the trigger logic.

Best,

Lew


Lew Riley<https://www.ursinus.edu/live/profiles/189-lew-riley>
Professor
Chair of Physics & Astronomy
Pre-Engineering Coordinator
484-762-4307
he|him
[cid:954eddbe-e563-492e-b81c-1eea26cd7272]
________________________________

**Comment by davidfokkema** [comment]
I confirmed that switching to A OR B seems to keep the previous trigger setting. Maybe mixing is not possible, indeed.

**Comment by rileyle** [comment]
Hi David,

I am in the lab playing with our 5443D, which I think is like yours but with 4 analog channels. I can’t reproduce the behavior you are seeing. When I disconnect A or B during “A OR B” triggering the unplugged channel stops triggering and the other continues. If I trigger on a single channel it behaves as expected. I don’t see any sign that it remembers earlier trigger settings. Not sure how to explain.

If you are stuck with preamp signals, you might experiment with reducing the high voltage. We operate at the low end of our HV range (900 V) when looking at cosmic rays to maximize the range of energy loss we can see.

I get an error code (invalid trigger) when I try A AND B. The AND condition can be determined in the pulse height data from each event, so this is maybe not important. As I read the application note on advanced triggering, I think AND requires both triggers to be active at the same time, which doesn’t work for level-mode triggering (window mode only, I think) and isn’t what we really want. Instead (I think) what we want in the case of AND are events in which we have both signals triggering any time during the sampling window. I hope I’m being clear. I’d be happy to meet via Zoom or Teams to chat.

The alpha membership is at this point prorated to something like $17 US, and there’s no additional registration fee for the workshop. It’d be great to have you if it fits your schedule.

Cheers,

Lew
________________________________

**Comment by davidfokkema** [comment]
Hi Lew,

Strange that you don’t see that behavior. Today was my last day at work for a few weeks (I’m taking some time off, this summer) but I brought home a new PicoScope we want to test for 4-channel measurements. It’s a 5442D, so the 60 MHz equivalent of your scope, I guess. Could it be that they behave differently? Or might it be a bug in the Pico drivers on my side? I’m on a Mac and there are no drivers available. The preliminary MacSDK only has one scope (not the 5000 series) and the ‘official’ way of getting everything to run on a Mac is installing the PicoScope beta version and copying drivers out of the app bundle. I did that once, quite some time ago. Maybe there was a bug in the driver which I’m still running into. I’ll check! This was what I saw today with two detectors (on A and B) with a sodium-22 source for coïncident 511 keV gammas in between:

Trigger on A: triggers on A
Trigger on B: triggers on B
Trigger on A OR B: triggers on B, only when I disconnect B (not A), triggering stops
Trigger on A: triggering resumes, connected B again
Trigger on A OR B: triggers on A, only when I disconnect A (not B), triggering stops.

I performed these actions in sequence. I’ll probably play around with the device a bit in the coming days so I will try and see if there is a difference between old and new ‘drivers’. I’ll try to connect some probes to an Arduino or something.

We’ll try your suggestion regarding the HV voltage, thanks!

I think you’re totally correct on the AND trigger issue. I didn’t appreciate the problem. We do not (only) want to have two simultaneous triggers (i.e. signals which are both above the threshold at the same time). Indeed, when A receives a pulse, we want to see if B receives a pulse some time later, like this:



This would be an interesting signal, but at no time do A and B trigger at the same time… Is this what you meant? Interesting problem… I think A or B would indeed be required, combined with a search of timestamps or event traces, just like you suggested. I could chat on Wednesday evening (for me). That would be between 18:00 - 20:00 UTC. Or Thursday, 7:00 - 15:00 UTC, but I’d guess that’s a bit early on your side.

Seems like an alpha membership is feasible, ;-). I’ll try to fit it in my schedule!

Best,
David


Verstuurd vanaf mijn iPad

**Comment by davidfokkema** [comment]
I confirmed that it must be a bug in old drivers. That is, testing in a new VM with new drivers shows the desired result: either A or B will trigger.

**Comment by rileyle** [comment]
Good to know.

I plan to test on a Linux box at some point. (Those may be the same drivers as macOS.)


Lew Riley<https://www.ursinus.edu/live/profiles/189-lew-riley>
Professor
Chair of Physics & Astronomy
Pre-Engineering Coordinator
484-762-4307
he|him
[cid:b35e20a7-cef5-4180-a1d5-ea30f8cd6773]
________________________________

**Pull request merged**
